### ISSUE TITLE
What's the meaning of Support Devices?

### ISSUE THREAD

**Issue by dobma** [stanfordmlgroup/chexpert-labeler#10]
Excuse me! Could you tell me what is support devices one of the 14 labels? She didn't give me the answer when I ask the Google. And I know rarely medical knowledge. Thanks!

**Comment by jirvin16** [comment]
Support devices includes devices like central lines, pacemakers, and ET tubes. See https://github.com/stanfordmlgroup/chexpert-labeler/blob/master/phrases/mention/support_devices.txt for a list of all the terms used by the labeler which fall into this category.
