### ISSUE TITLE
cannnot install 

### ISSUE THREAD

**Issue by kekeke29341** [stanfordmlgroup/chexpert-labeler#14]
I got an error. 
Please help><

<img width="1338" alt="スクリーンショット 2019-11-12 9 37 04" src="https://user-images.githubusercontent.com/1960224/68631938-080f2200-0530-11ea-9fc4-0579a2ffd40f.png">

**Comment by jirvin16** [comment]
If you haven't yet resolved this, this looks like an incorrect version of `negbio`. I'd suggest updating.

**Comment by TheRedMoon** [comment]
Do not use bioc==1.3 but instead use bioc==1.1.dev3. The 1.3 version is not compatible with netBio.

https://github.com/ncbi-nlp/NegBio/issues/32#issuecomment-502133836

You can look there for further information

**Comment by jirvin16** [comment]
?It looks like it is compatible with their Python 3.7 environment:

https://github.com/ncbi-nlp/NegBio/blob/master/environment3.7.yml#L18

Have you tested this with the packages in the CheXpert labeler environment?

**Comment by TheRedMoon** [comment]
Yes, I have. Ran against the same problem even after installing all the packages correctly. Downgrading from 1.3 to 1.1 fixed it for me (even though like you said it said it should work). I think negbio hasn't been upgraded to deal with the bioc 1.3 yet (correct me if I am wrong).

**Comment by jirvin16** [comment]
Got it, thanks for explaining. I'm not sure what's going on, but it may be a Python 3.6 vs. 3.7 issue. It seems like the current packages specified in the CheXpert labeler environment.yml are correct though. Did installing the conda environment from the environment.yml fail for you?

**Comment by TheRedMoon** [comment]
Could surely be the case. I think i was running on python 3.6. Yes, the environment installed correctly. I will try to use the project soon on a new clean pc and see if I will run against the same problem again.

**Comment by jirvin16** [comment]
Great, thanks. In that case going to close this issue for now.
