### ISSUE TITLE
Prerequisite steps also require activating the conda environment

### ISSUE THREAD

**Issue by MaxGhenis** [stanfordmlgroup/chexpert-labeler#21]
May be obvious to most users, but for completeness (and to save figuring out the environment name), I'd suggest adding `conda activate chexpert-label` between steps 3 and 4 in the README:
https://github.com/stanfordmlgroup/chexpert-labeler/blob/9668ef17ec36e489fab55a00aa0eace828bbaed2/README.md#L19-L29

**Comment by jirvin16** [comment]
Thanks so much for these suggestions! If you wouldn't mind making a quick PR with these changes, that'd be very helpful.

**Comment by MaxGhenis** [comment]
@jirvin16 sure, filed #22
