### ISSUE TITLE
What is the programming language used in negation.txt of patterns?

### ISSUE THREAD

**Issue by EricFu1120** [stanfordmlgroup/chexpert-labeler#23]
Hi Jeremy, I need to make some changes in the _negation.txt_ and _uncertainty.txt_ of _patterns_. So I want to figure out the programming language used in them. Thanks!

eg.
`# No definite XXX
({} > {} {lemma:/definite/}) > {dependency:/neg/} {}`

**Comment by jirvin16** [comment]
This should be a good resources to learn about these patterns:
https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/semgraph/semgrex/SemgrexPattern.html

**Comment by EricFu1120** [comment]
> This should be a good resources to learn about these patterns:
> https://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/semgraph/semgrex/SemgrexPattern.html

Thank you very much!
