### ISSUE TITLE
ValueError: Parser model has not been loaded.

### ISSUE THREAD

**Issue by binerone** [stanfordmlgroup/chexpert-labeler#24]
when i run with the command :
          python label.py --reports_path {reports_path}
here is the error: 

`Traceback (most recent call last):
  File "label.py", line 51, in <module>
    label(parser.parse_args())
  File "label.py", line 42, in label
    classifier.classify(loader.collection)
  File "/Users/binerone/test/chexpert-labeler/stages/classify.py", line 100, in classify
    self.parser.parse_doc(document)
  File "/Users/binerone/test/NegBio/negbio/pipeline/parse.py", line 55, in parse_doc
    tree = self.parse(text)
  File "/Users/binerone/test/NegBio/negbio/pipeline/parse.py", line 34, in parse
    nbest = self.rrp.parse(str(s))
  File "/Users/binerone/anaconda3/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/RerankingParser.py", line 614, in parse
    rerank = self.check_models_loaded_or_error(rerank)
  File "/Users/binerone/anaconda3/envs/chexpert-label/lib/python3.6/site-packages/bllipparser/RerankingParser.py", line 786, in check_models_loaded_or_error
    raise ValueError("Parser model has not been loaded.")
ValueError: Parser model has not been loaded.`

My os is Mac os, I can not solve this problem. Thanks for help.

**Comment by jirvin16** [comment]
Did you follow all 6 steps outlined in [the README](https://github.com/stanfordmlgroup/chexpert-labeler/blob/master/README.md)?

**Comment by binerone** [comment]
I have tried to execute the 6 steps in the readme, but when the execution reaches the third step, there is a problem:

`Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - ncurses==6.1=hf484d3e_1002
  - libedit==3.1.20170329=hf8c457e_1001
  - openssl==1.1.1f=h7b6447c_0
  - libffi==3.2.1=he1b5a44_1006
  - libstdcxx-ng==8.2.0=hdf63c60_1
  - jpype1==0.6.3=py36h9de70de_1001
  - tk==8.6.8=h84994c4_1000
  - sqlite==3.25.3=h67949de_1000
  - xz==5.2.4=h14c3975_1001
  - numpy==1.15.4=py36h8b7e671_1002
  - libgcc-ng==8.2.0=hdf63c60_1
  - readline==7.0=hf8c457e_1001
  - numpy-base==1.15.4=py36hde5b4d6_0
  - pandas==0.23.4=py36h637b7d7_1000
  - python==3.6.7=h0371630_0
  - libgfortran-ng==7.3.0=hdf63c60_5
  - zlib==1.2.11=h516909a_1006
  - gcc_linux-64==7.3.0=h553295d_9
  - gxx_linux-64==7.3.0=h553295d_9`

So, I manually created the virtual environment and manually installed the library in the "environment.yml".

Then, after performing steps 4-6 normally, an error occurred when running the label.py file.
