### ISSUE TITLE
Import error with bllipparser/_CharniakParser.so

### ISSUE THREAD

**Issue by tobiolatunji** [stanfordmlgroup/chexpert-labeler#3]
Hi. I've followed the instructions for the NegBio install. Everything works fine till step 5 where I get an import error.

`Download the GENIA+PubMed parsing model:`
`>>> from bllipparser import RerankingParser`
`>>> RerankingParser.fetch_and_load('GENIA+PubMed')`

Full traceback

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/negbio2.7/lib/python2.7/site-packages/bllipparser/__init__.py", line 399, in <module>
    from .RerankingParser import RerankingParser, Tree, Sentence, tokenize
  File "/anaconda3/envs/negbio2.7/lib/python2.7/site-packages/bllipparser/RerankingParser.py", line 19, in <module>
    from . import CharniakParser as parser
  File "/anaconda3/envs/negbio2.7/lib/python2.7/site-packages/bllipparser/CharniakParser.py", line 28, in <module>
    _CharniakParser = swig_import_helper()
  File "/anaconda3/envs/negbio2.7/lib/python2.7/site-packages/bllipparser/CharniakParser.py", line 24, in swig_import_helper
    _mod = imp.load_module('_CharniakParser', fp, pathname, description)
ImportError: dlopen(/anaconda3/envs/negbio2.7/lib/python2.7/site-packages/bllipparser/_CharniakParser.so, 2): Symbol not found: __ZNKSt5ctypeIcE13_M_widen_initEv
  Referenced from: /anaconda3/envs/negbio2.7/lib/python2.7/site-packages/bllipparser/_CharniakParser.so
  Expected in: /usr/lib/libstdc++.6.dylib
 in /anaconda3/envs/negbio2.7/lib/python2.7/site-packages/bllipparser/_CharniakParser.so

Seems it's some issue with how the package is compiled?

Mac Version 10.14, Anaconda3

**Comment by alistairewj** [comment]
Do you have XCode installed? At a guess it's trying to import a library that doesn't exist.

**Comment by tobiolatunji** [comment]
Yep, installed Xcode. Still fails. I switched to Linux and it installed fine.

**Comment by tobiolatunji** [comment]
New problem though, still with bllipparser.

(chexpert-label) /////projects/chexpert-labeler$ python
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bllipparser import RerankingParser
>>> RerankingParser.fetch_and_load('GENIA+PubMed')
Error downloading model (501 Not Implemented)

**Comment by tobiolatunji** [comment]
Error looks like it's coming from the bllipparser model downloader.

>>>from bllipparser import RerankingParser
>>>rrp = RerankingParser.fetch_and_load('WSJ-PTB3', verbose=True)
Model directory: /home/tobi/.local/share/bllipparser/WSJ-PTB3
Fetching model: WSJ-PTB3 from https://www.dropbox.com/s/ulcfs7my1ifriuu/BLLIP-WSJ-PTB3.tar.bz2?dl=1
`Error downloading model (501 Not Implemented)`

**Comment by alistairewj** [comment]
Are you behind a proxy? I think that might mess up the bllip parser download code. You should probably post this issue on their repo.

As a workaround, you could try downloading the compressed archive from that DropBox link yourself and extracting it into the `~/.local/share/bllipparser/GENIA+PubMed/` folder.

**Comment by tobiolatunji** [comment]
That worked. Thank you!!
