### ISSUE TITLE
How to run the labeler on GPU.

### ISSUE THREAD

**Issue by ashwanikumar04** [stanfordmlgroup/chexpert-labeler#31]
Hello:

When running the labeler on a laptop, it is taking too much time for a few thousand items. Is it possible to run the same on GPU?

Thanks

**Comment by jirvin16** [comment]
> Hello:
> 
> When running the labeler on a laptop, it is taking too much time for a few thousand items. Is it possible to run the same on GPU?
> 
> Thanks

Unfortunately the labeler cannot be run on GPU.

**Comment by ashwanikumar04** [comment]
Thanks for the reply.
