### ISSUE TITLE
Have stanford-corenlp-3.5.2.jar pre-downloaded in docker image

### ISSUE THREAD

**Issue by PabloMessina** [stanfordmlgroup/chexpert-labeler#42]
Hi, I'm using the dockerized version of the CheXpert labeler so as to run multiple instances in parallel, which is helping to save a lot of time. However, I've noticed that every time I run a docker container with cheXpert labeler, the file stanford-corenlp-3.5.2.jar gets downloaded. It happens every single time, so if I run 10 containers in parallel, that means 10 downloads in parallel. Even if I just want to run a cheXpert labeler container to label a single report, the file gets downloaded again.

When this happens, the log usually looks like this:

Downloading 'http://search.maven.org/remotecontent?filepath=edu/stanford/nlp/stanford-corenlp/3.5.2/stanford-corenlp-3.5.2.jar' -> '/root/.local/share/pystanforddeps/stanford-corenlp-3.5.2.jar'

This usually is not a problem (I've been downloading this file thousands of times already), but it certainly adds some network bandwidth overhead, it makes labeling a single report slower (10 seconds for the first report, from the second report onwards the penalty does not apply because the file is downloaded only once per run), and from time to time the run fails because the download attempt receives a 502 bad gateway response from the server.

**Question**: Would it possible to have stanford-corenlp-3.5.2.jar pre-downloaded within the CheXpert labeler docker image, so that it doesn't have to be downloaded again and again every time I run the container?

Thanks in advance.

**Comment by jirvin16** [comment]
Mentioning @jantrienes who developed the dockerized runtime (#32) in case they can help with this!

**Comment by jirvin16** [comment]
Thanks for the quick fix @jantrienes! @PabloMessina, please let me know if the PR fixes this for you.

**Comment by PabloMessina** [comment]
@jirvin16, yes, the quick fix seems to work. The logs indicating the download of the CoreNLP jar are gone. Thanks @jantrienes!
