### ISSUE TITLE
Compatibility with NegBio

### ISSUE THREAD

**Issue by cshivade** [stanfordmlgroup/chexpert-labeler#5]
Hello, 
It seems the NegBio underwent significant changes recently. This results in a bunch of errors. Can you please the update the repo to absorb those?

**Comment by alistairewj** [comment]
Can you provide any information about what the errors are? Traceback, etc?

**Comment by cshivade** [comment]
Thanks for the response. Specifically the following calls have changed in NegBIo:

Line 28 in load.py
Lines 100 to 104 in stages/classify.py

**Comment by cshivade** [comment]
I tried merging the pull request [here](https://github.com/stanfordmlgroup/chexpert-labeler/pull/4) and running it at my end. It addresses the issues in my prebious comment. It does throws a different error but does generate the output file labeled_reports.csv. Can you please add the expected output file for the [sample_reports.csv](https://github.com/stanfordmlgroup/chexpert-labeler/blob/master/sample_reports.csv) to this repo? That would help users verify if their output is correct. Thanks !

**Comment by jirvin16** [comment]
Great to hear! I've added the sample output file and seems the original issue is resolved, so closing this.
