### ISSUE TITLE
CheXpert-v1.0-small/train.csv missing values

### ISSUE THREAD

**Issue by KeremTurgutlu** [stanfordmlgroup/chexpert-labeler#9]
I am recently exploring data which is shared here in: https://stanfordmlgroup.github.io/competitions/chexpert/. Pathology labels mentioned in the article are either labeled as positive, negative or uncertain but when looking at csv files shared there are also NANs(missing values) present. How should we interpret these missing values? How it was done in the original baseline model? Thanks.

**Comment by jirvin16** [comment]
The missing values mean that no mention of the observation was extracted by the labeler in the report. We treat those cases as negative in the model presented in the paper.

**Comment by KeremTurgutlu** [comment]
Thanks a lot for the clarification :)

**Comment by jirvin16** [comment]
Glad to help! :)
